name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tamboon-testing:
    name: Tamboon Build & Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - uses: actions/cache@v2
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
    - name: Carthage
      run: |
        carthage bootstrap --platform iOS --use-xcframeworks --cache-builds
    - name: Build & Tests
      run: |
        set -o pipefail &&
          xcodebuild test \
            -workspace Tamboon.xcworkspace \
            -scheme Tamboon \
            -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' \
            | xcpretty

  tamboon-api-testing:
    name: TamboonAPI Build & Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Tests
      run: |
        set -o pipefail &&
          xcodebuild test \
            -workspace Tamboon.xcworkspace \
            -scheme TamboonAPI \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
            | xcpretty
