name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build & Tests
      run: |
        set -o pipefail && 
          xcodebuild test \
            -scheme Tamboon \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
            | xcpretty
